sitevision/envision

_docs/utils/sizing.md
docs/utils/sizing/index.html

Use of correct class names in documentation

---

package-lock.json

Some dependencies in package-lock are broken. Results in inconsistent package-lock.json file.

Replace broken package-lock.json file

---

_docs/components/dropdown.md
_docs/components/modal-dialog.md
_docs/utils/icons.md
_docs/utils/text.md
docs/components/dropdown/index.html
docs/components/modal-dialog/index.html
docs/utils/icons/index.html
docs/utils/text/index.html

Addresses minor errors in docs where faulty class names where in use.

---

_docs/components/modal-dialog.md
docs/components/modal-dialog/index.html

Updated docs with correct call to jQuery.fn.envDialog. Fixes #85

---

package-lock.json
package.json

Potential security vulnerability.

removed npm-run-all dependency

---

_docs/components/button-group.md
docs/components/button-group/index.html
src/scss/collapse.scss
src/scss/mixin/button.scss
src/scss/variable.scss

Added a $button-font-family variable.
Added env-button--success to button group documentation.
Collapse component now uses $collapse-toggle-duration when collapsing

Variable changes

---

_docs/utils/icons.md
docs/assets/envision/envision.css.map
docs/utils/icons/index.html

access env icons in sv doc #130

---

packages/envision/src/scss/collapse.scss
packages/envision/src/scss/feed.scss
packages/envision/src/scss/modal-dialog.scss
packages/envision/src/scss/popover.scss

Affected components:
Popover
Feed
Collapse
Dialog-modal

added line break to components

---

packages/envision/src/scss/collapse.scss
packages/envision/src/scss/feed.scss
packages/envision/src/scss/modal-dialog.scss
packages/envision/src/scss/popover.scss

Affect components
Collapse
Popover
Modaldialog
Feed

added ie11 word-wrap support

---

packages/envision/src/scss/feed.scss

Outside border removed. Will give pixel errors/horizontal alignment issues otherwise. Other borders set to transparent.

Change to transparent border in feed

---

.gitignore
package.json
packages/envision/src/scss/variable.scss

Updated gitignore
Remove erroneous flag to docker publish

Change font-sizes to be relative to base.

---

packages/envision-docs/src/pages/components/button.md
packages/envision-docs/src/pages/components/dropdown.md
packages/envision-docs/src/pages/utils/icons.md
packages/envision/src/scss/button.scss
packages/envision/src/scss/dropdown.scss
packages/envision/src/scss/icons.scss
packages/envision/src/scss/variable.scss

Ikoner i knappar funkar väldigt dåligt. Det här löser de flesta problemen.

APP-474 - Better defaults for icons in buttons

---

packages/envision-docs/src/pages/components/profile-image.md
packages/envision-docs/src/scss/demo.scss
packages/envision/src/scss/profile-image.scss

Buddy icon component

---

packages/envision-docs/src/scss/docs.scss
packages/envision/src/scss/base.scss

Only adjustments on documentation web - prepare for theme switching

Documentation themes

---

packages/envision-docs/src/pages/components/button.md
packages/envision-docs/src/pages/components/dropdown.md
packages/envision-docs/src/pages/components/table.md
packages/envision/src/scss/button-group.scss
packages/envision/src/scss/list.scss
packages/envision/src/scss/mixin/backdrop.scss
packages/envision/src/scss/table.scss
packages/envision/src/scss/variable.scss

- Button group fix for ghosts buttons
- Caption styling in table
- Modal backdrop as css-vars

Misc adjustments

---

packages/envision-docs/src/components/Header/index.js
packages/envision/src/scss/collapse.scss

Only hide collapse content when JS is active

Hide content for JS only

---

packages/envision/src/scss/button.scss
packages/envision/src/scss/form.scss
packages/envision/src/scss/util/text.scss

Reset and adjust button.env-link. Text-size-adjust is needed for iOS.

Styling links and buttons

---

packages/envision/src/scss/collapse.scss

Fix collapse

---

packages/envision/src/js/collapse.js

Ignore calls during animation

---

packages/envision/src/scss/form.scss
packages/envision/src/scss/mixin/form.scss

Added border color for checkbox/radio

Fix for validation state text color

---

packages/envision-docs/src/pages/components/cards.md
packages/envision-docs/src/scss/demo.scss
packages/envision-docs/src/scss/docs.scss
packages/envision/src/scss/base.scss
packages/envision/src/scss/cards.scss
packages/envision/src/scss/mixin/colors.scss
packages/envision/src/scss/variable.scss

Kolla igenom dokumentationen lite extra så det är begripligt. Mer text än vanligt.

Env 51 cards

---

packages/envision-docs/src/pages/utils/flexbox.md
packages/envision-docs/src/scss/demo.scss
packages/envision/src/scss/util/flexbox.scss

Refactor flex

---

packages/envision-docs/src/pages/utils/spacing.md
packages/envision/src/scss/util/spacing.scss

Negative margins

---

packages/envision-docs/src/pages/utils/colors.md

Kan vi beskriva det här bättre?

Add general colors in docs

---

packages/envision-docs/src/pages/components/dropdown.md
packages/envision-docs/src/pages/components/popover.md
packages/envision/src/scss/mixin/popout-menu.scss

Adjustments for better alignment in menu, adjusted documentation examples

Fix alignment, doc samples

---

packages/envision/src/js/dropdown.js
packages/envision/src/js/modal-dialog.js
packages/envision/src/js/popover.js
packages/envision/src/js/util/nodes.js
packages/envision/src/js/util/popper.js
packages/envision/src/scss/dropdown.scss

Moved modal and dropdown to body

---

packages/envision/src/scss/mixin/button.scss

ENV-149 Refactor button CSS

---

.eslintrc.json
packages/envision-docs/src/hooks/copyExample.js
packages/envision-docs/src/pages/components/image-slider.md
packages/envision-docs/src/pages/components/image-viewer.md
packages/envision-docs/src/pages/components/select.md
packages/envision/src/js/accordion.js
packages/envision/src/js/collapse.js
packages/envision/src/js/dropdown.js
packages/envision/src/js/image-slider.js
packages/envision/src/js/image-viewer.js
packages/envision/src/js/modal-dialog.js
packages/envision/src/js/popover.js
packages/envision/src/js/range-slider.js
packages/envision/src/js/select.js
packages/envision/src/js/tabs.js
packages/envision/src/js/util/nodes.js
packages/envision/src/js/util/util.js
packages/envision/src/scss/dropdown.scss

Also solves ENV-100 Prepare to remove jQuery dependency

Env 193 image slider refactor

---

packages/envision/src/scss/form.scss
packages/envision/src/scss/mixin/form.scss
packages/envision/src/scss/variable.scss

Make sure form inputs does not need env-form wrapping for style

ENV-244 form inputs refacoring

---

.github/workflows/build-envision-and-docs.yml

Reverts sitevision/envision#453

Revert "Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows"
